### ISSUE TITLE
not recommended

### ISSUE THREAD

**Issue by wolfpil** [s0ph1e/eml-reader#2]
I would not recommend this eml reader because it is useless:

1. it doesn't show the date,

2. it doesn't show the sender, forwarder, and recipient,

3. it doesn't wrap the lines of the eml files, so the lines are not completely visible,

4. and simply it doesn't work.

**Comment by s0ph1e** [comment]
Hi @wolfpil 
I've just checked it - it works as expected - renders content of eml file
However it doesn't show some fields - I have an issue for that #1

Thanks for your opinion and feel free to improve it

**Comment by wolfpil** [comment]
Closing #2 so qickly seems to be a sort of dishonesty and lack of interest, because #2 goes far beyond #1.

Further more:

5. it doesn't show the subject.

6. Seems you have checked http://eml.nepochataya.pp.ua. But I guess that the code there is different from the code you have publicized here.
Because the Ajax requests do not work with the published code here.

**Comment by s0ph1e** [comment]
* Code in repo an code on website is the same. I've checked it locally and for me it works fine. If you faced some errors - please provide details
* I've added your suggestions about subject and date to #1
* > it doesn't wrap the lines of the eml files, so the lines are not completely visible

   I can't understand what do you mean without details.
* > and simply it doesn't work

  I can't understand what do you mean without details

Please keep in mind that it is open source project and you are not forced to use my repo. If you don't like it - you can just ignore it and create new project.

Creating issues without details and using expressions like "it is not recommended", "it is useless", "it doesn't work" - is not good way for resolving issues. I would recommend to be more friendly in future and provide more details for issues. Here is nice article about contributing: https://opensource.guide/how-to-contribute/#communicating-effectively
