### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by wolfpil** [s0ph1e/eml-reader#5]
Because /src/app.js is directly running in the browser calling localhost:3000 I got

```
ReferenceError: require is not defined[Learn More]  app.js:2:1
   <anonymous> http://localhost:3000/src/app.js:2:1
```

**Comment by s0ph1e** [comment]
Hi @wolfpil 

`/src/app.js` should not be running directly in browser
App uses `/dist/app.js`, see https://github.com/s0ph1e/eml-reader/blob/d39b1c4fe5834e92de6e552f859b17b41e06cbba/views/index.html#L65

To build and run app please follow steps described in [readme](https://github.com/s0ph1e/eml-reader#install-and-run)
