### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by barrymichaeldoyle** [s0ph1e/eml-reader#6]
I get an error where the entity I'm trying to open is too large. Is there a workaround for this??

**Comment by s0ph1e** [comment]
Hi @barrymichaeldoyle 
I've not seen this error. Could you please provide steps to reproduce it?

**Comment by barrymichaeldoyle** [comment]
Drag an `.eml` file to open that is 1.3MB big.

**Comment by s0ph1e** [comment]
On website http://eml.nepochataya.pp.ua it was a problem with default file size 1MB in nginx config. I've updated it to 20MB - so now should be fine.

Another workaround can be setup your own server with this app
